[package]
name = "sandbox_yhyb_indtop"
version = "0.1.0"
edition = "2021"

[lib]
name = "sandbox_yhyb_indtop"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18", features = ["extension-module"] }
numpy = "0.18"
ndarray = "0.15"
rayon = "1.8"
memmap2 = "0.9"
hdf5-metno = { version = "0.12", features = ["static", "zlib"] }
arrow = "51.0"
parquet = "51.0"
chrono = "=0.4.39"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
